### ISSUE TITLE
screenshots / interaction examples requested

### ISSUE THREAD

**Issue by masukomi** [tionis/glyph#1]
This looks promising, but as with all knowledge bases, different ones work for different 🧠s. It's really difficult too tell what this is and what using it would be like without installing it and actually living with it for a bit. 

It would be very helpful if there were some screenshots, and maybe a quickie overview video on youtube or something to give folks like me a clue if this was worth us spending our time on, or something that just wouldn't work with our 🧠s.

**Comment by tionis** [comment]
That's a fair suggestion. The project is currently in a very early phase, and I will probably rename it soon.  
When the design is more fleshed out, and I have a more stable CLI Interface, I will update this issue.
But just to clarify: This tool is very simple and will stay CLI focused, with some golden workflows that are better supported than others. I will try to add modularity and user customization with scripts etc. in large parts of the program, but in its core I develop this for my personal workflow based on things I didn't like in other solutions.
Here are some things I am currently designing for:
- I will try to keep the wiki compatible with the following other Knowledge base Management Tools:
  - Obsidian
  - Vimwiki
  - GitJournal
  - MkDocs (kinda, I will add a script that transforms the file so that mkdocs can work with them, I may remove support for this in the future)
- The main functionality will work using just a git server (or git bundles) as backend, but things dealing with large files like the archive will work differently (the preferred approach for those is currently a backend based on bupstash/rclone)

**Comment by tionis** [comment]
Oh, and regarding intended workflow, when I'm on my laptop I always have a terminal window open somewhere or can open one very fast with one keystroke.  
So this project was mostly written to capture quick ideas and concepts in a structured manner for this, as well as more long form interlinked articles.
Now I'm primarily extending its functionality for management of my life by integrating Calendar and Contacts managing (not CalDAV/CardDAV-compatible).
I'm also experimenting with the managment of 'collections' for simple synchronization and managment of games/music/videos/pictures.

**Comment by tionis** [comment]
Update: I'm currently quite busy with other work, so the ETA for Version 1.0 is in a few months.  
So before the end of the year, the CLI interface will be too unstable for other users.

**Comment by tionis** [comment]
After doing some thinking regarding the design of the tool repo itself, I decided that a screencast or similar example wouldn't really fit, as the interactions between glyph and its modules are difficult to show in general.
The module based design will instead focus on letting the user write scripts that embed better purpose built tools for differing data types. This means for example instead of writing a new contact management tool, you could just write a wrapper script around an existing one, which auto commits changes into a submodule. Glyph would then ensure that the submodule stays synced across your devices.
So instead of focusing on single interactions, I want glyph to make writing small wrapper script easier.
To achieve this, I will write some general documentation with example use cases that I'm using myself and link to several other projects for use cases that are not fulfilled by the example modules.
This will include for example the wiki module, which will soon be exported into a separate project for a better separation of concerns.  
I will close this for now, please reopen this or a new issue if there are any questions.
If anyone reading this has additional input for example use cases or the design, please open an issue or simply contact me on matrix: https://matrix.to/#/#tionis:matrix.org .

**Comment by masukomi** [comment]
just as an aside, since i don't know where else to put it 

CLI Only, captures quick notes / ideas, modular integrations == !@$# YES SIGN ME UP.  

I dunno if your ultimate interface / interaction model will work with my 🧠 but you should know that you're not the only one who thinks something like you described is a great way to work. 😉

**Comment by tionis** [comment]
Nice to hear, always happy to hear from people that want to use similar tools.  
I'll ping you once I've refactored the wiki code and added the documentation.

**Comment by tionis** [comment]
Just to give a quick example, I did a short screencast of me using the wiki module as well as the currently unpublished dev module:
https://asciinema.org/a/EWqmdXqKDU0r4sOuYNd04uKZQ
